[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
whitelist_sale = "C8sbuNSCxsqDZdLSqBi7LUBgTYRtjoqgyLARdMq36pvK"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/emil/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"


[[test.genesis]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
program = "metadata.so"

[test.validator]
reset = true

